# Generated by Django 2.2.5 on 2020-07-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200711_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_varification_key',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
