# Generated by Django 2.2.5 on 2020-07-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_varification_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_varification_key',
            new_name='email_verification_key',
        ),
    ]
