# Generated by Django 2.2.5 on 2020-07-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200703_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(related_name='rooms', to='rooms.Amenity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(related_name='rooms', to='rooms.Facility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ManyToManyField(related_name='rooms', to='rooms.RoomType'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rule',
            field=models.ManyToManyField(related_name='rooms', to='rooms.Rule'),
        ),
    ]
