# Generated by Django 2.2.5 on 2020-07-03 07:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200703_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
