# Generated by Django 2.2.5 on 2020-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20200712_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('canceld', 'Canceld')], default='pending', max_length=12),
        ),
    ]
